services:
  - type: web
    name: productos-app
    runtime: node
    repo: https://github.com/xXelghaleXx/Lab09-solnub.git
    branch: main
    buildCommand: npm rebuild sqlite3 && npm install && npm install ejs
    startCommand: node server.js
    envVars:
      - key: AWS_ACCESS_KEY_ID
        value: tu-key
      - key: AWS_SECRET_ACCESS_KEY
        value: tu-secret
      - key: AWS_REGION
        value: us-east-2
      - key: S3_BUCKET_NAME
        value: imgbucktadrian
      - key: NODE_ENV
        value: production
